- di/inject_adapters.go
- di/inject_application.go
- di/wire.go
- di/wire_gen.go
- internal/ptr.go
- service/adapters/blobs/storage.go
- service/adapters/blobs/storage_test.go
- service/adapters/mocks/blob_storage_mock.go
- service/app/application.go
- service/app/queries/create_history_stream_test.go
- service/app/queries/get_blob.go
- service/app/queries/get_blob_test.go
- service/domain/blobs/replication/downloader.go
- service/domain/blobs/size.go
- service/domain/blobs/size_or_want_distance_test.go
- service/domain/messages/blobs_get.go
- service/domain/messages/blobs_get_test.go
- service/domain/replication/manager_test.go
- service/ports/rpc/handler_blobs_get.go
- service/ports/rpc/handler_blobs_get_test.go
- service/ports/rpc/handler_create_history_stream_test.go
Blobs are sent in chunks to avoid using up too much wire time in one
handler.
> Implement the blobs.get port

- cmd/ssb-test/main.go
- di/inject_adapters.go
- di/wire_gen.go
- service/adapters/blobs/storage.go
- service/adapters/blobs/storage_test.go
- service/domain/blobs/replication/common.go
- service/domain/blobs/replication/downloader.go
- service/domain/blobs/replication/manager.go
- service/domain/blobs/replication/manager_test.go
- service/domain/blobs/replication/wants.go
- service/domain/blobs/replication/wants_test.go
- service/domain/messages/blobs_createWants.go
This implements replying to "wants" messages with "has" messages. "Wants" messages are received through `blobs.createWants` stream initiated by the local node and have to trigger a reply with a "has" message through `blobs.createWants` stream initiated by the remote node.
> Reply to "wants" messages with "has" messages

- service/adapters/bolt/no_tx_want_list_repository.go
This function for now has a side effect of changing the database even
though in theory it should be operating in read only mode.
> Fix database is modified when read only

- .github/workflows/ci.yml
Right now it shows up in various places as "Build" which isn't really
what it does.
> Make pipeline name more readable

- Makefile
- di/inject_adapters.go
- di/inject_application.go
- di/inject_config.go
- di/inject_formats.go
- di/inject_ports.go
- di/inject_pubsub.go
- service/adapters/mocks/blob_downloaded_pubsub.go
- service/domain/transport/rpc/connection_id.go
Linting problems fixed:
- fixed the comments ignoring certain lines
- removed incorrect assignment to an unused variable
- defined a separate type to avoid collisions when writing context values
> Update linter and fix linting problems

- internal/set.go
- internal/set_test.go
- service/adapters/bolt/feed_repository.go
- service/adapters/bolt/social_graph_repository.go
- service/adapters/bolt/social_graph_repository_test.go
- service/app/commands/handler_follow.go
- service/app/commands/handler_redeem_invite.go
- service/domain/feeds/contact.go
- service/domain/feeds/contact_test.go
- service/domain/feeds/content/contact.go
- service/domain/feeds/content/contact_test.go
- service/domain/feeds/content/transport/mapping_contact.go
- service/domain/feeds/content/transport/mapping_contact_test.go
- service/domain/feeds/feed_test.go
- service/domain/graph/graph.go
- service/domain/graph/graph_test.go
Contact messages are now correctly parsed and interpreted. Each contact message is treated as a set of actions which should be performed on a contact such as:
- follow a target
- unfollow a target
- block a target
- unblock a target
One contact message can contain multiple actions eg. block and unfollow. Follow/unfollow are governed by field "following". Block/unblock are governed by field "blocking". Fields are mapped as follows:
- following == nil   => []
- following == true  => [follow]
- following == false => [unfollow]
- blocking  == nil   => []
- blocking  == true  => [block]
- blocking  == false => [unblock]
Updates are therefore atomic eg. a message may update one field but leave the other field untouched.
Some combinations of actions are logically suspicious eg. follow and block …
> Fix the way contact messages are handled

- service/domain/graph/graph.go
- service/domain/graph/graph_test.go
Blocks are now analysed when generating the social graph. If a contact is blocked the edge will not be followed. Local blocks take priority and always block the feed.
> Take blocks into account when generating the social graph

- service/adapters/bolt/feed_repository.go
- service/adapters/bolt/feed_repository_test.go
- service/adapters/bolt/read_feed_repository_test.go
- service/app/commands/common.go
- service/app/commands/handler_follow.go
- service/app/commands/handler_publish_raw.go
- service/app/commands/handler_redeem_invite.go
- service/app/commands/message_buffer.go
It makes the interface confusing, after all the feed is always created for you and it is unclear why you would want to return a different feed struct.
> Do not return a feed when updating it

- service/adapters/bolt/social_graph_repository.go
- service/adapters/bolt/social_graph_repository_test.go
- service/domain/feeds/contact.go
- service/domain/feeds/contact_test.go
- service/domain/graph/graph.go
- service/domain/graph/graph_test.go
Author of a contact (person who it belongs to/who created it) can't be the same as the person that the contact is pointing at (target). If someone accidently blocked themselves this could create some weird behaviour with removing feeds.
> Change contacts so that author can't be the target

- service/domain/feeds/contact.go
- service/domain/feeds/contact_test.go
Some clients emit contact messages following their own feed for some
reason.
> Author of a contact can be the same as its target

- di/wire.go
- di/wire_gen.go
- service/adapters/bolt/read_contacts_repository.go
- service/app/commands/message_buffer.go
- service/app/commands/message_buffer_test.go
- service/domain/feeds/feed.go
- service/domain/messagebuffer/buffer.go
- service/domain/messagebuffer/buffer_test.go
- service/domain/replication/ebt/session.go
- service/domain/replication/gossip/manager.go
- service/domain/replication/gossip/manager_test.go
Message buffer can now handle messages arriving out of order from many
peers. Dropped the optimization which took buffer state into account as
this whole mechanism will probably need rework anyway and was
malfunctioning.
> Message buffer rework

- service/domain/feeds/content/transport/mapping_about.go
- service/domain/feeds/content/transport/mapping_post.go
- service/domain/feeds/content/transport/mapping_post_test.go
- service/ports/pubsub/room_attendant_events_test.go
Partially related to https://github.com/planetary-social/scuttlego/issues/69.
Full fix probably involves actually scanning the markdown for links. It is unclear where this format is coming from and where it is specified.
> Don't return errors for mentions which are an object

- service/app/commands/handler_rooms_alias_register.go
- service/app/commands/handler_rooms_alias_register_test.go
- service/app/commands/handler_rooms_alias_revoke.go
- service/app/commands/handler_rooms_alias_revoke_test.go
Async functions shouldn't terminate with an error.
> Fix commands related to aliases

- service/app/queries/create_history_stream.go
- service/domain/transport/rpc/connection_test.go
- service/domain/transport/rpc/request_stream.go
- service/domain/transport/rpc/request_stream_test.go
- service/domain/transport/rpc/request_streams_test.go
A sequence of in-stream messages and then a remote termination could cause the last of the in-stream messages to be lost due to a race condition.
> Fix a duplex race condition

- di/inject_application.go
- di/inject_ports.go
- di/wire_gen.go
- service/app/application.go
- service/ports/network/connection_establisher.go
- service/ports/network/discoverer.go
- service/ports/network/listener.go
The application struct is supposed to define commands and queries which can be called externally. This is slightly different from normal approach but this is what we decided at some point. Because of this commands which are strictly internal were removed. This should reduce confusion from the bindings perspective.
Added a missing DownloadFeed command to the application struct.
> Cleanup application struct

- service/app/commands/message_buffer.go
- service/domain/feeds/content/transport/mapping_contact_test.go
- service/domain/feeds/content/transport/marshaler.go
Since the transactions are batched it was previously possible that messages will be dropped from the buffer when the transaction was repeated - the transactions weren't idempotent. This has been fixed.
Additionally previously encountering a malformed known message meant that an error is returned. This has now been changed and malformed messages are persisted without errors. They will have to be rescanned using migrations if the code parsing messages is at fault when the error occurs.
> Accelerate replication

- di/inject_application.go
- di/wire.go
- di/wire_gen.go
- service/adapters/mocks/feed_repository.go
- service/app/application.go
- service/app/commands/handler_publish_raw.go
- service/app/commands/handler_publish_raw_as_identity.go
- service/app/commands/raw_message_publisher.go
- service/app/commands/raw_message_publisher_test.go
This command can be used to publish messages using the specified identity to its main feed. This is needed for testing the bindings as Swift requires a function like this.
> Add PublishRawAsIdentity command

- service/ports/network/listener.go
This is not documented but closing the context passed to Listen doesn't close the listener.
See https://github.com/golang/go/issues/28120.
> Close the listener when context expires

- .github/workflows/ci.yml
The cache is reusable and useful across go.sum files as far as I know and our config was wrongly ordered anyway so this option had no effect.
> Don't try to scope Github Action caches using go.sum

- .github/workflows/ci.yml
- Makefile
I think since Makefile contains some tool versions it also needs to be included in cache. I also hardcoded the other tool version to keep things consistent.
> Include Makefile in cache

- migrations/migrations.go
- migrations/migrations_test.go
- service/app/commands/handler_run_migrations.go
- OnRunning is only called when a particular migration has to be
executed so if all migrations were already executed this will not be
called, if status loading fails for a migration this callback will not
be triggered
- OnError is only called when a particular migration fails, if this
callback is triggered it is only triggered once and is the last
callback to be triggered
- OnDone is only called once there are no more migrations remaining to
be executed (including if there are no migrations to consider) and
there were no errors so if this callback is triggered it is triggered
only once and is the last callback to be triggered
Example valid call sequences:
- no migrations:
- OnDone(count=0)
- we had three migrations, they all had to be run and executed correctly:
- OnRunning(index=0, …
> Call progress callback when migrations are executed

- cmd/log-debugger/debugger/debugger_test.go
- fixtures/fixtures.go
- service/adapters/badger/ban_list_repository.go
- service/adapters/badger/feed_repository.go
- service/adapters/badger/feed_repository_test.go
- service/adapters/badger/pub_repository.go
- service/adapters/badger/social_graph_repository.go
- service/adapters/badger/utils/bucket.go
- service/adapters/badger/wanted_feeds_repository.go
- service/adapters/mocks/raw_message_identifier.go
Badger keys can't be reused without copying them. Matt's database
somehow got corrupted after adding a feed to the ban list. While the
feed data was there all the referenced messages were not. All this data
is removed in transactions so the only explanation that I can think
about is that we are illegally reusing keys which seems to be true.
Added some unrelated tests that I wrote while looking for the bug. They
are unrelated because this bug is hard to test reliably.
> Make sure that we are not illegaly reusing badger keys

- README.md
I believe there was some confusion about this. This change clarifies
that go-ssb's code wasn't copied and instead scuttlego still relies on
go-ssb by calling it like every other library.
> Clarify how go-ssb is reused in the README 

- .golangci.yaml
- di/inject_adapters.go
- di/inject_application.go
- di/inject_badger.go
- di/inject_config.go
- di/inject_formats.go
- di/inject_migrations.go
- di/inject_networking.go
- di/inject_ports.go
- di/inject_pubsub.go
Removed not needed ignore tags and one set that was found to be unused.
> Enable linter for wireinject build tags

- integration_tests/receive_log_test.go
- service/adapters/badger/feed_repository.go
- service/adapters/badger/feed_repository_test.go
- service/adapters/badger/receive_log_repository.go
- service/adapters/badger/receive_log_repository_test.go
The receive log used to break when messages were removed. Alternative
solution would be to skip messages not found in the message repository
but I can't find a solid reason for not removing receive log entries and
going with that approach.
> Delted messages are removed from receive log

- service/app/commands/handler_migration_import_data_from_gossb.go
Let's take this out of the other pull request. The upside is that I've never observed this failing... maybe because the error handling is completely borked.
> Fix incorrect error handling during migration

- service/app/commands/handler_migration_import_data_from_gossb.go
- service/app/commands/handler_migration_import_data_from_gossb_test.go
- service/domain/feeds/feed.go
Ignored messages were treated as successes and put in the receive log. The receive log would then break because those messages didn't actually exist in the database.
Fixes https://github.com/planetary-social/scuttlego/issues/200.
In reality we should solve this at the domain level and this bug stems from the fact that we didn't.
> Fix receive log data corruption on migration

- service/adapters/badger/feed_repository.go
- service/adapters/badger/feed_repository_test.go
- service/adapters/mocks/feed_repository.go
- service/app/commands/common.go
- service/app/commands/handler_migration_import_data_from_gossb.go
- service/app/commands/handler_migration_import_data_from_gossb_test.go
- service/app/common/common.go
Sometimes messages are quietly forked and we don't know which is the
correct one. If we detect a message conflicts with an existing message
we drop all messages with sequence >= sequence of that message so let
the conflic resync from the network.
Related to https://github.com/planetary-social/scuttlego/issues/197.
> Detect and handle forks during migration

- service/domain/messagebuffer/buffer.go
- service/domain/messagebuffer/buffer_test.go
Message buffer (which uses FeedMessages) often contains duplicate message sequences because it may replicate the same message from multiple peers.
A bug in the code caused the code to stop when duplicate sequences were encountered.
> Fix handling duplicate sequences in message buffer

- di/config.go
The default hops value didn't match the comment.
> Fix default hops value

- fixtures/fixtures.go
- internal/slice.go
- service/domain/mocks/connection.go
- service/domain/replication/ebt/adapters.go
- service/domain/replication/ebt/replicator_test.go
- service/domain/rooms/tunnel/adapters.go
- service/domain/rooms/tunnel/adapters_test.go
- service/domain/transport/rpc/connection_test.go
- service/domain/transport/rpc/mux/mocks/response_writer_closer.go
- service/domain/transport/rpc/mux/mux.go
- service/domain/transport/rpc/mux/mux_test.go
- service/domain/transport/rpc/request_stream.go
- service/domain/transport/rpc/request_stream_test.go
- service/domain/transport/rpc/request_streams.go
- service/domain/transport/rpc/response_streams.go
- service/domain/transport/rpc/response_streams_test.go
- service/domain/transport/rpc/transport/raw_message.go
- service/domain/transport/rpc/transport/raw_message_test.go
- service/ports/rpc/handler_blobs_createWants.go
- service/ports/rpc/handler_blobs_createWants_test.go
- service/ports/rpc/handler_blobs_get.go
- service/ports/rpc/handler_blobs_get_test.go
- service/ports/rpc/handler_create_history_stream.go
- service/ports/rpc/handler_create_history_stream_test.go
Messages which are requests based on headers can have body type set to binary due to the fact that they could be follow-up messages in duplex streams.
> Set correct response body type

- service/domain/graph/builder.go
- service/domain/graph/builder_test.go
We were accidently getting contacts of children just to check that they are too far away in the social graph.
> Don't needlessly query contacts storage
